"""add career_analyses table

Revision ID: 2edb966a3529
Revises: 5f1991f27e16
Create Date: 2026-08-19 14:56:06.449878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2edb966a3529'
down_revision: Union[str, None] = '5f1991f27e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('certificates', sa.JSON(), nullable=False),
    sa.Column('language_score_text', sa.String(length=100), nullable=True),
    sa.Column('project_count', sa.Integer(), nullable=False),
    sa.Column('competition_count', sa.Integer(), nullable=False),
    sa.Column('has_intern_experience', sa.Boolean(), nullable=False),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=False),
    sa.Column('readiness_level', sa.String(length=20), nullable=False),
    sa.Column('weak_areas', sa.JSON(), nullable=False),
    sa.Column('recommended_certificates', sa.JSON(), nullable=False),
    sa.Column('recommended_projects', sa.JSON(), nullable=False),
    sa.Column('recommended_learning_areas', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_analyses_user_id'), 'career_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_analyses_user_id'), table_name='career_analyses')
    op.drop_table('career_analyses')
    # ### end Alembic commands ###
