"""add is_verified to users

Revision ID: 8b177f000415
Revises: 2edb966a3529
Create Date: 2026-08-19 21:06:14.788423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b177f000415'
down_revision: Union[str, None] = '2edb966a3529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default: 기존에 가입된(테스트) 계정들이 NOT NULL 제약에 걸리지 않도록 false로 채운다.
    # 실제 운영에서는 기존 미인증 계정에게 재인증을 안내해야 할 수 있다.
    op.add_column(
        'users',
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
